package com.odsaprojects.prod.entities;
// Generated 07-feb-2018 21:45:12 by Hibernate Tools 5.1.4.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * Jugadores generated by hbm2java
 */
@Entity
@Table(name = "jugadores")
@NamedQueries({ @NamedQuery(name = "Jugadores.findAll", query = "SELECT j FROM Jugadores j WHERE j.estado = 1"),
	@NamedQuery(name = "Jugadores.findByCedula", query = "SELECT j FROM Jugadores j WHERE j.cedula LIKE :cedula AND j.estado = 1"),
	@NamedQuery(name = "Jugadores.findByEquipo", query = "SELECT j FROM Jugadores j WHERE j.equipos.id = :equipo AND j.estado = 1"),
	@NamedQuery(name = "Jugadores.findById", query = "SELECT j FROM Jugadores j WHERE j.id = :id AND j.estado = 1")})
public class Jugadores implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private Long id;
	private String nombres;
	private String apellidos;
	private String cedula;
	private int edad;
	private String camiseta;
	private Equipos equipos;
	private int estado;

	public Jugadores() {
	}

	public Jugadores(String nombres, String apellidos, String cedula, int edad, String camiseta, Equipos equipos) {
		this.nombres = nombres;
		this.apellidos = apellidos;
		this.cedula = cedula;
		this.edad = edad;
		this.camiseta = camiseta;
		this.equipos = equipos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "nombres", nullable = false, length = 128)
	public String getNombres() {
		return this.nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	@Column(name = "apellidos", nullable = false, length = 256)
	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	@Column(name = "cedula", nullable = false, length = 11)
	public String getCedula() {
		return this.cedula;
	}

	public void setCedula(String cedula) {
		this.cedula = cedula;
	}

	@Column(name = "edad", nullable = false)
	public int getEdad() {
		return this.edad;
	}

	public void setEdad(int edad) {
		this.edad = edad;
	}

	@Column(name = "camiseta", nullable = false, length = 2)
	public String getCamiseta() {
		return this.camiseta;
	}

	public void setCamiseta(String camiseta) {
		this.camiseta = camiseta;
	}

	@ManyToOne()
	@JoinColumn(name = "idEquipos")
	public Equipos getEquipos() {
		return equipos;
	}

	public void setEquipos(Equipos equipos) {
		this.equipos = equipos;
	}

	public int isEstado() {
		return estado;
	}

	public void setEstado(int estado) {
		this.estado = estado;
	}

}
